import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import './styles/app.css';
import Header from './components/header';
import { cn } from './lib/heplers';
import Footer from './components/footer';
import { getMainSeo } from './lib/supabase/queries/server/main-info';

export async function generateMetadata(): Promise<Metadata> {
  const { error, data } = await getMainSeo();

  if (error) {
    return {
      title: 'Test Steel Lady',
      description: 'Generated by create next app',
    };
  }

  return {
    title: data.site_name + ' | JavaScript разработчик',
    description: data.site_description,
    openGraph: {
      images: [data.open_graph_image],
    },
  };
}

const sans = Source_Sans_3({
  subsets: ['latin', 'cyrillic'],
  weight: 'variable',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={cn(
          `relative
        bg-bg
        z-0
        min-h-svh
        tracking-wide
        text-white`,
          sans.className
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
