import type { Metadata } from 'next';
import '@/app/styles/app.css';
import Header from '@/app/components/header';
import { cn } from '@/app/lib/heplers';
import Footer from '@/app/components/footer';
import { getMainSeo } from '@/app/lib/supabase/queries/server/main-info';
import { ViewTransitions } from 'next-view-transitions';
import {
  shadows_into_light,
  sourse_sans_3,
} from '@/app/assets/fonts';

export async function generateMetadata(): Promise<Metadata> {
  const { error, data } = await getMainSeo();

  if (error) {
    return {
      title: 'Test Steel Lady',
      description: 'Generated by create next app',
    };
  }

  return {
    title: data.site_name + ' | JavaScript разработчик',
    description: data.site_description,
    openGraph: {
      images: [data.open_graph_image],
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={cn(
          `scroll-smooth dark`,
          sourse_sans_3.variable,
          shadows_into_light.variable
        )}
      >
        <body
          className={cn(
            `relative
        bg-bg
        z-0
        min-h-svh
        tracking-wide
        text-white`
          )}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ViewTransitions>
  );
}
